[package]
name = "my_zine_web"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
zino = { version = "0.20", features = ["axum"] }
axum = "0.6"